### ISSUE TITLE
xilinx.jpg and pynqz1.jpg files not found

### ISSUE THREAD

**Issue by mslavescu** [yunqu/dac_2018#2]
After installation at this path there is no:
/home/xilinx/jupyter_notebooks/dac_2018/images/xilinx.jpg
/home/xilinx/jupyter_notebooks/dac_2018/images/pynqz1.jpg

Used in dac_contest.ipynb:
image_path = get_image_path('xilinx.jpg')
image_path = get_image_path('pynqz1.jpg')

**Comment by npurusho** [comment]
Please try the updated notebook. It should be fixed
